### ISSUE TITLE
Unrecognized option "extras" under..

### ISSUE THREAD

**Issue by netfarma** [jbouzekri/ConfigKnpMenuBundle#11]
Hi.
It is not possible to set "estras" parameter described in https://github.com/KnpLabs/KnpMenu/blob/1.1.x/src/Knp/Menu/MenuItem.php

```php
->arrayNode('extras')
                        ->prototype('scalar')
                        ->end()
                    ->end()
```
 should be added to 
https://github.com/jbouzekri/ConfigKnpMenuBundle/blob/master/Config/Definition/Builder/MenuNodeDefinition.php

**Comment by jbouzekri** [comment]
Hi @kemor.
Would you be able to make a pull request ?
Thanks

**Comment by netfarma** [comment]
I have made a PR. It was my first. I was able to do it in the fifth attempt :)

**Comment by jbouzekri** [comment]
@netfarma Many thanks. I won't be able to look it over at work. I will do that this evening after work.

**Comment by jbouzekri** [comment]
Ok I have merged a new branch created from your pull request. So I cleaned the windows carriage return and added a unitary test at the same time. You are still credited for the commit ;)

I will do a new release in a few minutes.

Thanks.
