### ISSUE TITLE
Wrong Node Definition for the 'extras' item

### ISSUE THREAD

**Issue by thedamnedrhino** [jbouzekri/ConfigKnpMenuBundle#17]
The prototype of the __'extras'__ item in [`MenuNodeDefinition`](https://github.com/jbouzekri/ConfigKnpMenuBundle/blob/master/Config/Definition/Builder/MenuNodeDefinition.php#L70) is set as `'scalar'`. However this is not necessarily the case. Take the `extras->routes` parameter for instance. It is an array of matching routes with the menu element. However each route can be defined as an array with the keys _'route'_, _'pattern'_ and _'parameters'_. So the items in `'extras'` are not necessarily scalar.

**Comment by jbouzekri** [comment]
I am not sure to understand what you mean.

The `extras` attribute is referring to the one from the KnpMenu NodeItem : https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/MenuItem.php#L56

and you have a test to validate that it accepts an array of variable parameters.
https://github.com/jbouzekri/ConfigKnpMenuBundle/blob/master/Tests/Provider/ConfigurationMenuProviderTest.php#L114
