### ISSUE TITLE
Deprecation warnings when using this bundle with symfony 4.4

### ISSUE THREAD

**Issue by meedkruu** [jbouzekri/ConfigKnpMenuBundle#21]
I use this bundle with Symfony 4.4 and get the following deprecation warnings.
- Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead
- The "Jb\Bundle\ConfigKnpMenuBundle\Event\ConfigureMenuEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

**Comment by jbouzekri** [comment]
@meedkruu Sorry for my late answer. I just made a PR https://github.com/jbouzekri/ConfigKnpMenuBundle/pull/22. Are you able to test it before I merge ?

**Comment by meedkruu** [comment]
The PR looks good. We are going to test it and let you know then.

**Comment by meedkruu** [comment]
All tests passed and deprecation warnings are gone :-)

**Comment by jbouzekri** [comment]
@meedkruu : thank you. I just pushed a 6.0 release : https://github.com/jbouzekri/ConfigKnpMenuBundle/releases/tag/6.0
It should be available through packagist in a few minutes.
