### ISSUE TITLE
Unable to install on Symfony 6

### ISSUE THREAD

**Issue by Flower7C3** [jbouzekri/ConfigKnpMenuBundle#23]
jbouzekri/config-knp-menu-bundle 6.0 requires symfony/event-dispatcher ^4.0|^5.0 -> found symfony/event-dispatcher[v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but these were not loaded, likely because it conflicts with another require.

**Comment by jbouzekri** [comment]
The bundle has not been updated to support SF 6.x if you look into the composer.json : https://github.com/jbouzekri/ConfigKnpMenuBundle/blob/master/composer.json

Would you be able to work on a PR to add this ?

**Comment by Flower7C3** [comment]
@jbouzekri I will try.

**Comment by jbouzekri** [comment]
@Flower7C3 thank you. I have just merged your PR (sorry for my tardiness). I am going to flag a new release.
