### ISSUE TITLE
Label translation

### ISSUE THREAD

**Issue by bubnovKelnik** [jbouzekri/ConfigKnpMenuBundle#7]
I want to set labels in yml not as final "Label", but as translatable tags, like "navigation.seo", etc.
Please, inject translate service into Builder and translate labels.

I will make a fork soon and ask for pull merge

**Comment by jbouzekri** [comment]
Is it mandatory ? 

It has been some time since I used this bundle but I think the translation was handled on the template side by the template in KnpMenuBundle.

Maybe here : https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/Resources/views/knp_menu.html.twig#L101

**Comment by bubnovKelnik** [comment]
It is no good to modify template in vendor dir.
I also don`t want to use custom menu.html.twig  -  I will miss all updates from KnpMenuBundle or KnpMenu

**Comment by jbouzekri** [comment]
I am not talking about modifying in vendor dir of course.

You could extend the twig template to override the block label. It seems to be the cleanest solution instead of adding another dependancy to the bundle.

**Comment by bubnovKelnik** [comment]
Found a solution, thank you!

**Comment by bubnovKelnik** [comment]
In config.yml
twig:
    ...
    paths:
        "%kernel.root_dir%/../vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views": knp_menu

in my custom knp_menu.html.twig
{% extends "@knp_menu/knp_menu.html.twig" %}

{% block label %}{% if options.allow_safe_labels and item.getExtra('safe_label', false) %}{{ item.label|raw|trans }}{% else %}{{ item.label|trans }}{% endif %}{% endblock %}
